const fs = require('fs')

/**
 * Retrieve the Daedalus contract hash from the local out file generated by `deployDaedalusContract()`
 */
function getDaedalusHash () {
  try {
    return fs.readFileSync('daedalusHash', { encoding: 'utf8' })
  } catch (err) {
    if (err.code === 'ENOENT') {
      console.error('daedalusHash file does not exist. Run deployDaedalusContract(0, true) to generate')
    } else {
      console.error(err)
    }
  }
}

module.exports = getDaedalusHash